# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='amount',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='activity',
            name='quantity',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='activity',
            name='detail',
            field=models.TextField(max_length=1000),
        ),
    ]
