# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180508_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='actid',
            new_name='aid',
        ),
    ]
