# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180508_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.IntegerField(),
        ),
    ]
