# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180508_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('reservation_no', models.CharField(default=web.models.handle_reservation_number, max_length=15)),
                ('checkin_date', models.CharField(max_length=100)),
                ('checkout_date', models.CharField(max_length=100)),
                ('detail_data', models.CharField(max_length=100)),
                ('act_data', models.CharField(max_length=100)),
                ('b_price', models.FloatField()),
                ('status', models.IntegerField(choices=[(1, 'Confirm'), (2, 'Operated'), (3, 'Cancelled'), (4, 'Completed')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
