# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 03:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_bookingactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingactivity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
